### PR TITLE
adds to README, runs php-cs-fixer, and fixes frontend controller

### PR DESCRIPTION
**Pull request by bshaffer**
Just some small tweaks that I hope improve this library:
- Adds "Get Started" section to README
- ensures Front Controller executes the app
- renames some parameters
- ran `php-cs-fixer`

This looks great! To improve it, I would like to include an endpoint that will generate a SAML assertion so we can quicky and easily test the token endpoint.

### CODE REVIEW

**Comment by aacotroneo** [comment]
Let me know when you want me to merge this one.

About the endpoint, I can start with a static saml assertion sample.

**Comment by bshaffer** [comment]
merge it now! :-P

As for the assertion... I will comb over [the spec](https://tools.ietf.org/html/draft-ietf-oauth-saml2-bearer-23) and see if I can't find a way to generate an accurate SAML assertion. I apologize, but I am having trouble understanding the limitation here, and why we can't do a real one.

**Comment by aacotroneo** [comment]
The main problem is that a saml Assertion has one target.

Say you have 3 servers: IDP (simplesamlphp), OauthServer, ClientA

ClientA says to IDP: I want a samlAssertion. 
IDP returns (over a redirect) "This is an assertion for ClientA from IDP (user is Joe)".

That is the basic case in Saml. But, If you want to give that one to the OauthServer, (in strict mode) it will complain that the assertion is made for ClientA.

To make it standard:
- ClientA should make the assertion itself directed to OauthServer - (misses the point of using saml in the first place?)
- ClientA should ask the IDP a token for the OauthServer. I think this one is good when ClientA is not a SP. If it is a SP it may need another assertion for itself.

There is definitely something I dont get :)

**Comment by bshaffer** [comment]
maybe what you don't get is the fact that the IDP is trusted by the OAuth Server, and so the OAuth Server most likely knows the IDP's public key, can validate the assertion was granted from that IDP, and so happily accepts the Saml Assertion from ClientA without complaint.

**Comment by aacotroneo** [comment]
That's what the strict=false setting does. It doesn't validate target, but does validates signature. A delicate thing it does not check is expiration date. 
See some comments here: https://github.com/aacotroneo/saml2-bearer-server/blob/master/inst/saml_settings.php

For me that approach makes sense, but I'm not sure if the draft allows it.

**Comment by bshaffer** [comment]
what exactly is the oauth server complaining about?  What is it expecting instead?  I see the list of checks (audience, issuer, and destination) and I don't see why we couldn't have all of those check out in this use case.

**Comment by aacotroneo** [comment]
It expects like you say (audience, issuer, and destination)  to match itself.

You can of course make such an assertion yourself. What I can't figure is how to make a flow that makes sense within an existing saml2 infrastructure. May be that's not the intended usage, or I am too focused on my domain.

**Pull request merged**
